### ISSUE TITLE
Full list of situations where "contents of a message can't be altered"

### ISSUE THREAD

**Issue by Weishaupt** [MicrosoftDocs/OfficeDocs-Exchange#1965]
The `DisclaimerFallbackAction` explains that 

> There are situations where the contents of a message can't be altered (for example, the message is encrypted).

Unfortunately this is quite vague. As Disclaimers might be related to security notices I'd like to understand in what exact situations a content of a message can't be altered.

Personally I can only think of two such instances:
1. The message is encrypted
2. The message is signed

Is this the complete list of situations or are there other situations. Right now I'm unable to make an informed decision on the value I should set `DisclaimerFallbackAction` to.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8d245fb-eb4b-879d-4da8-7e7be414a179
* Version Independent ID: a05b031b-db9a-6f28-09a3-68640eb9c570
* Content: [Mail flow rule actions in Exchange Online](https://docs.microsoft.com/en-us/exchange/security-and-compliance/mail-flow-rules/mail-flow-rule-actions)
* Content Source: [Exchange/ExchangeOnline/security-and-compliance/mail-flow-rules/mail-flow-rule-actions.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/mail-flow-rules/mail-flow-rule-actions.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@Weishaupt Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Weishaupt** [comment]
In the meantime I received some Non-Delivery-Reports (NDR) which were also wrapped. I can't explain to myself why those were wrapped, as the content is not signed. Maybe Exchange Online handles NDRs differently?

**Comment by Weishaupt** [comment]
@scanum Any update on the investigation?

**Comment by scanum** [comment]
@Weishaupt Dario submitted a PR for this! Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by Weishaupt** [comment]
@scanum Please reopen. As I mentioned in my comment it looks like NDRs also can't be altered even though NDRs are neither signed nor encrypted. Thus it looks like a full list of all applicable cases is still not provided. I'd love someone with knowledge of the code base provide an answer as I'm unable to identify where content cannot be altered by the transport rule.
