### ISSUE TITLE
Send-as not supported ?

### ISSUE THREAD

**Issue by joker226** [MicrosoftDocs/OfficeDocs-Exchange#73]
Send-as permission works great cross-premises, you need to ensure that permission exists in the sending user’s forest, as described in https://support.microsoft.com/en-us/help/3064053/overview-of-delegation-in-an-office-365-hybrid-environment.
So, are you sure it's still not supported ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a1959e5-a0c2-3431-4fe4-3e4e7843a594
* Version Independent ID: 33dd3686-3b92-0393-837b-dfd76152151f
* Content: [Permissions in Exchange hybrid deployments](https://docs.microsoft.com/en-us/exchange/permissions#feedback)
* Content Source: [Exchange/ExchangeHybrid/permissions.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/permissions.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by AndreaBarr** [comment]
@joker226 Thank you for your feedback

I want to make sure this supported or not supported send-as permission is addressed properly so I'm sending this over to the SharePoint team for investigation and updating of the document. 

I was able to get this into the backlog for the SharePoint team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by AndreaBarr** [comment]
@tseward is investigating this issue.

**Comment by dariomws306** [comment]
I think the same apply for automapping and folder permissions.

**Comment by Thesmast** [comment]
Is there any update concerning the permissions topic?

**Comment by dariomws306** [comment]
As we can see in the KB3064053 is not fully supported by Microsoft but it should work.

I still have a pending task to fully test it.

**Comment by vbhadauria22** [comment]
We have checked send as permission as per mentioned in this article but its not working, however send as working if we run cmdlet like this.

Add-RecipientPermission -Identity "ONPREM1" -Trustee EXO1 -AccessRights SendAs

**Comment by dstrome** [comment]
The topic includes our current support stance for Send-As permissions in a hybrid environment.
