### ISSUE TITLE
Need to sync PF proxy mailbox

### ISSUE THREAD

**Issue by mohan1921** [MicrosoftDocs/OfficeDocs-Exchange#951]
I just figured that we need to first sync PF proxy mailboxes from Exchange 2010 to the cloud before running the set-organizationconfig command in Step 5. Otherwise it gives error as object not found. can we get this step verified and update this document?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45f5e210-5945-277a-12dc-f1eae01ba403
* Version Independent ID: a9a867e0-e3eb-ffbb-2013-47707a6b4364
* Content: [Configure legacy on-premises public folders for a hybrid deployment](https://docs.microsoft.com/en-us/exchange/collaboration-exo/public-folders/set-up-legacy-hybrid-public-folders#feedback)
* Content Source: [Exchange/ExchangeOnline/collaboration-exo/public-folders/set-up-legacy-hybrid-public-folders.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/collaboration-exo/public-folders/set-up-legacy-hybrid-public-folders.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@mohan1921 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by pirutgrrrl** [comment]
@mohan1921 also having this same issue.  Noticed that there wasn't a step to mount the new DB so did that.  Let me know if this DB shouldn't be mounted. I did this as a troubleshooting step as the Set-Org in Step 5 wasn't able to see PFMailbox1.

**Comment by VLG17** [comment]
@mohan1921 the article states that you first need to wait for AD synchronization to take place or force it:

"You must wait until ActiveDirectory synchronization has completed to see the changes. This process can take up to 3 hours to complete. If you don't want to wait for the recurring synchronizations that occur every three hours, you can force directory synchronization at any time."

**Comment by scanum** [comment]
@mohan1921 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by pirutgrrrl** [comment]
@scanum This issue doesn't appear to be resolved.   This is the second time I'm looking here for help on this same step.  If a dirsync needs to be complete, it should be added after step 4 as well.  I have forced sync and waited an entire day in a two-server environment and this is still an issue.  When running set-organizationconfig  to Exchange online from step 5 receive:
Couldn't find object "PFMailbox1". Please make sure that it was spelled correctly or specify a different object.

**Comment by VLG17** [comment]
@pirutgrrrl Your two-server environment is Exchange 2010 CAS/MBX? You're using ADConnect for doing the directory sync, right? Did you also make sure that you are syncing the OU which contains the PFMailbox1 which you created? If not, you need to specify that explicitely and then force a sync or wait for a sync cycle to pass.

**Comment by pirutgrrrl** [comment]
@VLG17 - that did it for me, thank you.  I wasn't syncing the built-in users OU.  Does it matter if the DB is mounted or not?  If it needs to be mounted, we should get that added to the cmdlet

**Comment by VLG17** [comment]
@pirutgrrrl I'm happy to hear that fixed the issue for you. I don't have an easy way to test this, so i cannot say for sure, but i guess for the syncronization part it does not need to be mounted, because you just need to sync the AD object. In order to access actual data from the PF Mailbox, of course it needs to be mounted.
